services:
  eureka-server:
    build: ./microservice-eureka
    ports:
      - "8761:8761"

  api-gateway:
    build: ./microservice-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  config-server:
    build: ./microservice-config
    ports:
      - "8888:8888"

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: coursesDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa1234
    ports:
      - "5432:5432"

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: studentDb
      MYSQL_ROOT_PASSWORD: sasa1234
    ports:
      - "3307:3306"

  course-service:
    build: ./microservice-course
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
      - config-server
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/coursesDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sasa1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  student-service:
    build: ./microservice-student
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - config-server
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/studentDb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sasa1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
