
services:
  config-server:
    build:
      context: ./microservice-config
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-network

  eureka-server:
    build:
      context: ./microservice-eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    depends_on:
      - config-server
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888

  student-service:
    build:
      context: ./microservice-student
    container_name: student-service
    ports:
      - "8090:8090"
    networks:
      - microservices-network
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka

  course-service:
    build:
      context: ./microservice-course
    container_name: course-service
    ports:
      - "9090:9090"
    networks:
      - microservices-network
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka

  gateway:
    build:
      context: ./microservice-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - eureka-server
      - student-service
      - course-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka

networks:
  microservices-network:
    driver: bridge
