version: '3.9'

services:
  eureka-server:
    build: ./microservice-eureka
    ports:
      - "8761:8761"
    networks:
      - app-network

  api-gateway:
    build: ./microservice-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - course-service
      - student-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - app-network

  config-server:
    build: ./microservice-config
    ports:
      - "8888:8888"  # Exponiendo el puerto 8888
    networks:
      - app-network  # Asegúrate de que esté en la misma red
    environment:
      - SPRING_PROFILES_ACTIVE=native  # Asegúrate de que el perfil nativo esté activo
    volumes:
      - ./configurations:/configurations  # Montando la carpeta de configuraciones (si la tienes localmente)


  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: coursesDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa1234
    ports:
      - "5432:5432"
    networks:
      - app-network

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: studentDb
      MYSQL_ROOT_PASSWORD: sasa1234
    ports:
      - "3307:3306"
    networks:
      - app-network

  course-service:
    build: ./microservice-course
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
      - config-server
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/coursesDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sasa1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - app-network

  student-service:
    build: ./microservice-student
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - config-server
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/studentDb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sasa1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
