server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: 'http://student-service:8090'
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: 'http://student-service:8090'
          predicates:
            - Path=/api/course/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # Conexión a Eureka
