server:
  port: 9090

spring:
  application:
    name: msvc-course
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/coursesDb # Cambiado a "postgres-db"
    username: postgres
    password: sasa1234
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: course-service # Opcional, solo para identificar
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # Usar "eureka-server" según Docker
